### ISSUE TITLE
package.json & database.js issue

### ISSUE THREAD

**Issue by cyril2day** [catalyst-technologies/feathers-chat-pgsql#1]
there are dependencies missing or not included in package.json. Such are knex, feathers-knex, pg and pg-promise. Aside from that, a confusing parameter is passed on `app.get('db_config')` at line 5 of src/database.js. It should be `app.get('postgres')`  where `postgres` is the JSON key property name of the postgres client entry, as defined on default.json at line 10 of config/default.json.

**Comment by chumheramis** [comment]
On it brodie.

**Comment by chumheramis** [comment]
It is all done now.
